### ISSUE TITLE
C++ : Basic Data Types

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#10]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Basic Data Types](https://www.hackerrank.com/challenges/c-tutorial-basic-data-types/problem?isFullScreen=true)

**Comment by abhi887449** [comment]
Please assign this task to me

**Comment by Riddhi9570** [comment]
@abhi887449 I have assigned you the issue #9. Sorry, I cannot assign you multiple issues from the same repository at a time. Once you complete that issue, you can claim other issue if it is open. Thank you. All the best!

**Comment by Sowham-3098** [comment]
Please assign this issue to me under Hacktoberfest Tag. You can assign me any problem for C++language.

**Comment by Sowham-3098** [comment]
Thank You @Riddhi9570

**Comment by Sowham-3098** [comment]
@Riddhi9570 Please tell me what I have to do next. Is my process is correct to creating a pull request ? I am a newbie. Please help.

**Comment by Riddhi9570** [comment]
> @Riddhi9570 Please tell me what I have to do next. Is my process is correct to creating a pull request ? I am a newbie. Please help.

@Sowham-3098 Thanks for asking! yes, it's correct.

**Comment by Sowham-3098** [comment]
Now can I update Readme.md file with the problem and the solution link?
