### ISSUE TITLE
Vector Sort (STL) in CPP

### ISSUE THREAD

**Issue by Sowham-3098** [Riddhi9570/HackerrankPracticeProblems#101]
Please Create a Folder in CPP named "STL"
And I want to contribute Vector Sort Problem's Solution in that code.
Problem Link : https://www.hackerrank.com/challenges/vector-sort/problem

**Comment by Sowham-3098** [comment]
Please assign this to me and tag it The hacktoberfest Level.
Thnak you

**Comment by Riddhi9570** [comment]
@Sowham-3098 You can do both the task together.
