### ISSUE TITLE
C++ : Deque-STL

### ISSUE THREAD

**Issue by Rohan-G** [Riddhi9570/HackerrankPracticeProblems#108]
@Riddhi9570
Want to work on this hackerrank problem : https://www.hackerrank.com/challenges/deque-stl/problem?isFullScreen=true

**Comment by Riddhi9570** [comment]
@Rohan-G Hey, Thanks for raising an issue! How many issues you have completed from this repo?

**Comment by Rohan-G** [comment]
> @Rohan-G Hey, Thanks for raising an issue! How many issues you have completed from this repo?

Only 1 PR till now

**Comment by Riddhi9570** [comment]
@Rohan-G Go ahead!👍
