### ISSUE TITLE
C++ : Conditional Statements

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#11]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Conditional Statements](https://www.hackerrank.com/challenges/c-tutorial-conditional-if-else/problem?isFullScreen=true)

**Comment by abhi887449** [comment]
Please assign this task to me

**Comment by Riddhi9570** [comment]
@abhi887449 and @Sowham-3098 you both have been assigned another issue, so I cannot assign you this issue at this time. Once that issue gets completed, ping me here if no one else has claimed this isssue, it will be asssigned on first-cum-first-serve-basis.

**Comment by Rohan-G** [comment]
Can I work on this for hacktoberfest?
