### ISSUE TITLE
C++: Class

### ISSUE THREAD

**Issue by R0merol** [Riddhi9570/HackerrankPracticeProblems#117]
I'd like to solve the Class challenge

**Comment by Riddhi9570** [comment]
@R0merol Hey, Thanks for contributing.
Note- It is considered a good practice to first wait till the issue is assigned to you, before working on it.

**Comment by R0merol** [comment]
Ahh, I'm sorry. I got a little too excited hehe. Thanks for merging the PR! Please don't forget to label it :)

**Comment by Riddhi9570** [comment]
No problem! @R0merol Just keep it in mind the next time you contribute to any repo. Happy Coding😃!
