### ISSUE TITLE
Maps-stl

### ISSUE THREAD

**Issue by Dhruv-Mahajan1** [Riddhi9570/HackerrankPracticeProblems#119]
Write a solution to this Hackerrank problem : [Link](https://www.hackerrank.com/challenges/cpp-maps/problem?isFullScreen=true)
@Riddhi9570 Please assign this issue 
Thanks!

**Comment by Riddhi9570** [comment]
Hey, Thanks for raising an issue!
Unfortunately, I cannot assign more than two issues for Hacktoberfest contribution to the same contributor. You may look into some other repositories for hacktoberfest. Thanks!

**Comment by Dhruv-Mahajan1** [comment]
No problem 👍
