### ISSUE TITLE
C++ : For Loop

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#12]
Write your solution to this C++ problem of hackerrank:-
Problem link : [For Loop](https://www.hackerrank.com/challenges/c-tutorial-for-loop/problem?isFullScreen=true)

**Comment by abhi887449** [comment]
Please assign this task to me

**Comment by Sowham-3098** [comment]
Please assign this task for me under Hacktoberfest tag.I will solve this problem as soon as possible.

**Comment by Dhruv-Mahajan1** [comment]
Hey, @Riddhi9570 since this issue hasn't been allotted to anyone, can I work on it?
Thanks!

**Comment by Riddhi9570** [comment]
Hey, @Dhruv-Mahajan1 yes, you may work on it. I didn't assigned the issue to them since they have been working on another issue. Thanks!
