### ISSUE TITLE
JAVA : Java Stdin and Stdout II

### ISSUE THREAD

**Issue by AmanGit010** [Riddhi9570/HackerrankPracticeProblems#123]
I would like to add solution for this problem from HackerRank for Java. @Riddhi9570 please assign me this issue, i have no issue assigned to me as of now, one PR got merged 🥳.

Link to problem - https://www.hackerrank.com/challenges/java-stdin-stdout/problem?isFullScreen=true

**Comment by AmanGit010** [comment]
I am contributing to Hacktoberfest, please assign the tag to this issue.

**Comment by Riddhi9570** [comment]
Hey, @AmanGit010  congratulations that your one PR got merged 🥳. Nice to know that you are again up for the contribution to the repo😃. But the hackerrank problem which you have raised is already present in the repo [here](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/Java/Introduction/StdIn_StdOut.java). Please bring an another problem for contribution. Thanks😃!

**Comment by AmanGit010** [comment]
As you can see in the image that there are two different problems for Java Stdin and Stdout. In Stdin and Stdout I, we have to print only 3 integers and in Stdin Stdout II we have to print an integer, double, and string. @Riddhi9570 

![image](https://user-images.githubusercontent.com/102356628/193417655-43ac5f18-e58b-4cee-a448-2c3c7e567e39.png)

**Comment by Riddhi9570** [comment]
@AmanGit010 
Java Stdin and Stdout I problem has been raised in the issue #20 
Java Stdin and Stdout II problem has been addressed in the PR #59.

**Comment by AmanGit010** [comment]
Ohh, i didn't see that. Thanks
