### ISSUE TITLE
Java: Java Datatypes

### ISSUE THREAD

**Issue by Anjali2201** [Riddhi9570/HackerrankPracticeProblems#127]
Problem Link:
https://www.hackerrank.com/challenges/java-datatypes/problem?isFullScreen=true

Problem is already solved by me. Just have to upload it. Could you assign it to me?

**Comment by Riddhi9570** [comment]
@Anjali2201 
Hey, Thanks for raising an issue!
Unfortunately, this problem statement has already been raised in another issue #26. 
You may take another hackerrank problem, raise an issue and make a PR only when it gets assigned to you.
Thanks! Happy Coding😃!

**Comment by Anjali2201** [comment]
I have added one more practice problem of python: arithmetic operator in the same pr. I guess that question is still not solved. Should i raise another issue?

**Comment by Riddhi9570** [comment]
Sorry, that problem is also raised in issue #37. Please make sure that the problem is not already raised in an issue or present in the repo. Once you have checked, you can raise a new issue. Thanks!

**Comment by Riddhi9570** [comment]
Also, please delete the commit you made earlier before making a new PR.
