### ISSUE TITLE
C++ : Functions

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#13]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Functions](https://www.hackerrank.com/challenges/c-tutorial-functions/problem?isFullScreen=true)

**Comment by abhi887449** [comment]
Please assign this task to me

**Comment by Sowham-3098** [comment]
You can assign this task to me. Please add the Hacktoberfest tag to this solution.

**Comment by Amarendra-ai** [comment]
I would like to contribute towards this problem, please assign this task to me.

**Comment by Riddhi9570** [comment]
@Amarendra-ai are you a hacktoberfest contributor?

**Comment by Amarendra-ai** [comment]
> @Amarendra-ai are you a hacktoberfest contributor?

Yes
