### ISSUE TITLE
Array left rotation in Java

### ISSUE THREAD

**Issue by dmanocha464** [Riddhi9570/HackerrankPracticeProblems#132]
### Hackerrank problem link

https://www.hackerrank.com/challenges/array-left-rotation/problem

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by dmanocha464** [comment]
@Riddhi9570 where should I add solution to this problem? it's related to array and I will be using Java language.

**Comment by Riddhi9570** [comment]
> @Riddhi9570 where should I add solution to this problem? it's related to array and I will be using Java language.

First make sure that your forked repo is up-to-date with the original repo. You will find a folder for Data Structures inside the root directory. Create a folder named "Array" inside the "Data Structures" folder, and add your file "Left Rotation.java". Thanks!
