### ISSUE TITLE
The blunder SQL problem add

### ISSUE THREAD

**Issue by ashavijit** [Riddhi9570/HackerrankPracticeProblems#138]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/the-blunder/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=24-hour-campaign

### Issue Checklist

* [ ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [X] Your forked repo is up-to-date with the the origin remote.
* [ X] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [X ] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [X ] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
@ashavijit 
Hey, Thanks for raising an issue!
Unfortunately, the hackerrank problem which you have raised is already present in the repo here. Please bring an another problem for contribution. Thanks😃!
