### ISSUE TITLE
New Companies SQL problem add 

### ISSUE THREAD

**Issue by ashavijit** [Riddhi9570/HackerrankPracticeProblems#146]
### Hackerrank problem linn

https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true
Provide your hackerrank problem link here.

### Issue Checklist

* [X] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [X] Your forked repo is up-to-date with the the origin remote.
* [ ] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [ ] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
@ashavijit Hey, Thanks for raising an issue!
But the hackerrank problem stated by you is already present in the repo.
Please claim or raise another issue.
