### ISSUE TITLE
Python : Runner-Up Score

### ISSUE THREAD

**Issue by yashkc2025** [Riddhi9570/HackerrankPracticeProblems#148]
### Hackerrank problem link

https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem

### Issue Checklist

- [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
- [X] Your forked repo is up-to-date with the the origin remote.
- [X] Have you checked that the hackerrank problem you are raising is not already present in the repo?
- [X] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

- [X] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
@yashkc2025 
Hey, Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
