### ISSUE TITLE
C++ : CPP Exception Handling

### ISSUE THREAD

**Issue by ag-yash** [Riddhi9570/HackerrankPracticeProblems#149]
Given below is the problem link. Please assign me this problem. I am a Hacktoberfest contributor :)

https://www.hackerrank.com/challenges/cpp-exception-handling/problem?isFullScreen=false

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

**Comment by Riddhi9570** [comment]
Hey @ag-yash , Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
