### ISSUE TITLE
C++ : Arrays Introduction

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#15]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Arrays Introduction](https://www.hackerrank.com/challenges/arrays-introduction/problem?isFullScreen=true)

**Comment by Csrivastava003** [comment]
I would like to work on this issue under Hacktoberfest

**Comment by Sowham-3098** [comment]
Please assign this task to me and add the tag Hacktoberfest.

**Comment by akshatjain1004** [comment]
Hey @Riddhi9570 since this issue hasn't been allotted to anyone, can I work on it?

**Comment by Riddhi9570** [comment]
@akshatjain1004 Since I have alloted another issues to @Csrivastava003 and @Sowham-3098 , and I can assign only one issue to a contributor at a time, I can assign this issue to you.

**Comment by Riddhi9570** [comment]
@akshatjain1004 are you a hacktoberfest contributor?

**Comment by akshatjain1004** [comment]
> @akshatjain1004 are you a hacktoberfest contributor?

Yes I'm contributing for hactoberfest 2022. Thank you so much for the issue :)
