### ISSUE TITLE
Python: No idea!

### ISSUE THREAD

**Issue by PurviSaini** [Riddhi9570/HackerrankPracticeProblems#152]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/no-idea/problem?isFullScreen=true
### Issue Checklist

* [ ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?
NA

**Comment by Riddhi9570** [comment]
@PurviSaini 
It's great that you contributed to the repo twice😃🥳.
Unfortunately, I cannot assign you more than two issues for this repo. 
You may look into some other repos for hackrtoberfest contribution.
Thanks😃!All the best!

**Comment by ShivayeModi** [comment]
@Riddhi9570 Can you assign this issue to me. I am eager to contribute to this Hackerrank problem

**Comment by PurviSaini** [comment]
> @PurviSaini It's great that you contributed to the repo twice😃🥳. Unfortunately, I cannot assign you more than two issues for this repo. You may look into some other repos for hackrtoberfest contribution. Thanks😃!All the best!

No problem, Thankyou so much for the considering the previous contribution!!

**Comment by Riddhi9570** [comment]
@ShivayeModi 
I've assigned you the issue and you may please go ahead!
Happy Coding😃!

**Comment by ShivayeModi** [comment]
@Riddhi9570 
I have solved the given problem, you can review my pull request now.
Thanks 😃
