### ISSUE TITLE
JAVA: Java Currency Formatter

### ISSUE THREAD

**Issue by AmanGit010** [Riddhi9570/HackerrankPracticeProblems#153]
### Hackerrank problem link

https://www.hackerrank.com/challenges/java-currency-formatter/problem?isFullScreen=true

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

@Riddhi9570 please assign me this issue. There is no issue assigned to me as of now, and there is no previous issue related to this problem.

**Comment by Riddhi9570** [comment]
Hey @AmanGit010 , Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
