### ISSUE TITLE
C++ : Variable Sized Arrays

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#16]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Variable Sized Arrays](https://www.hackerrank.com/challenges/variable-sized-arrays/problem?isFullScreen=true)

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Can you please assign this issue to me as part of Hacktoberfest 2022
