### ISSUE TITLE
C++: Structs

### ISSUE THREAD

**Issue by R0merol** [Riddhi9570/HackerrankPracticeProblems#160]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/c-tutorial-struct/problem

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.
N/A

**Comment by R0merol** [comment]
I'd like to be asigned this problem please!

**Comment by Riddhi9570** [comment]
@R0merol 
Hey, Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
