### ISSUE TITLE
Searching Algorithm C++

### ISSUE THREAD

**Issue by sambhavgupta0705** [Riddhi9570/HackerrankPracticeProblems#167]
### Hackerrank problem link
 https://www.hackerrank.com/challenges/missing-numbers/problem?isFullScreen=true
Provide your hackerrank problem link here.

### Issue Checklist

* [ ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [✔ ] Your forked repo is up-to-date with the the origin remote.
* [✔ ] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [✔ ] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [✔] Are you a Hacktoberfest Contributor?

**Comment by sambhavgupta0705** [comment]
Hey ,Please assign this issue to me!

**Comment by Riddhi9570** [comment]
Hey, @sambhavgupta0705  Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Since you have raised an issue for a new domain, you need to create a new folder.
Happy Coding😃!

**Comment by Riddhi9570** [comment]
Hey, @sambhavgupta0705, A new folder has been created for algorithms and you can put your files into it. Before that, please make sure that your forked repo is up-to-date with the original repo. Thanks!

**Comment by VedantBandeJain** [comment]
Hello ,please assign this issue to me
