### ISSUE TITLE
C++ : Overloading Ostream Operator

### ISSUE THREAD

**Issue by ag-yash** [Riddhi9570/HackerrankPracticeProblems#168]
Please assign me this problem.
### Hackerrank problem link

https://www.hackerrank.com/challenges/overloading-ostream-operator/problem?isFullScreen=true

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

**Comment by Riddhi9570** [comment]
Hey @ag-yash , Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
