### ISSUE TITLE
C++ : StringStream

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#17]
Write your solution to this C++ problem of hackerrank:-
Problem link : [StringStream](https://www.hackerrank.com/challenges/c-tutorial-stringstream/problem?isFullScreen=true)

**Comment by sumitbishti** [comment]
Please assign this issue to me under hacktoberfest tag.

**Comment by Csrivastava003** [comment]
I would like to work on this issue under hacktoberfest

**Comment by Riddhi9570** [comment]
@sumitbishti Sorry, I cannot assign you multiple issues from the same repository at a time. Once you complete that issue, you can claim any other open issue.

**Comment by sumitbishti** [comment]
> @sumitbishti Sorry, I cannot assign you multiple issues from the same repository at a time. Once you complete that issue, you can claim any other open issue.

Fair enough

**Comment by Csrivastava003** [comment]
This issue has not been labeled under the hacktoberfest?

**Comment by Csrivastava003** [comment]
New Pr with resolved conflicts has been made
