### ISSUE TITLE
C++: Searching

### ISSUE THREAD

**Issue by Csrivastava003** [Riddhi9570/HackerrankPracticeProblems#176]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/sherlock-and-array/problem?isFullScreen=true
### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Csrivastava003** [comment]
Please assign this issue to me. @Riddhi9570

**Comment by Riddhi9570** [comment]
Hey, @Csrivastava003  Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!

**Comment by Csrivastava003** [comment]
The pull request has been made regarding the issue.

**Comment by Csrivastava003** [comment]
@Riddhi9570  Thanks for allowing the contribution for Hacktoberfest.
Would love to contribute in the repo after Hacktoberfest too.

**Comment by Riddhi9570** [comment]
> @Riddhi9570 Thanks for allowing the contribution for Hacktoberfest. Would love to contribute in the repo after Hacktoberfest too.

@Csrivastava003 Thanks for your valuable contribution! Would love to see you after hacktoberfest! Happy Coding😃!
