### ISSUE TITLE
C++: Accessing Inherited Functions

### ISSUE THREAD

**Issue by gaurangk19** [Riddhi9570/HackerrankPracticeProblems#180]
### Hackerrank problem link

https://www.hackerrank.com/challenges/accessing-inherited-functions/problem

### Issue Checklist

* [X] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [X] Your forked repo is up-to-date with the the origin remote.
* [X] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [X] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [X] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by gaurangk19** [comment]
Hey @Riddhi9570 I would love to work on this :-)

**Comment by Riddhi9570** [comment]
Hey, @gaurangk19  Thanks for raising an issue!
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
