### ISSUE TITLE
SQL :Select By ID

### ISSUE THREAD

**Issue by AyushJain001** [Riddhi9570/HackerrankPracticeProblems#182]
### Hackerrank problem link
https://www.hackerrank.com/challenges/select-by-id/
Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/select-by-id/
### Issue Checklist

* [x ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [ x] Your forked repo is up-to-date with the the origin remote.
* [ x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x ] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [ x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
@AyushJain001 
It's great that you contributed to the repo twice😃🥳.
Unfortunately, I cannot assign you more than two issues for this repo for hacktoberfest. 
You may look into some other repos for hackrtoberfest contribution.
Thanks😃!All the best!

**Comment by AyushJain001** [comment]
Thanks  for the opportunity.🙌
