### ISSUE TITLE
Java: Java Anagrams

### ISSUE THREAD

**Issue by AditUB** [Riddhi9570/HackerrankPracticeProblems#193]
### HackerRank problem link

https://www.hackerrank.com/challenges/java-anagrams/problem?isFullScreen=true

### Issue Checklist

* [x] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?
No

**Comment by AditUB** [comment]
Can I contribute to this?

**Comment by Riddhi9570** [comment]
@AditUB Go for it 👍
