### ISSUE TITLE
Algorithims topic - Dynamic programming subtopic

### ISSUE THREAD

**Issue by sasidharswarangi** [Riddhi9570/HackerrankPracticeProblems#194]
### Hackerrank problem link
[https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=dynamic-programming](https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=dynamic-programming
)
### Issue Checklist

* [ no ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [ yes ] Your forked repo is up-to-date with the origin remote.
* [ yes ] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [ yes ] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [ yes ] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
Hey @sasidharswarangi Please mention the exact hackerrank problem link you want to contribute.
