### ISSUE TITLE
For Loop

### ISSUE THREAD

**Issue by HarshitaSadadekar** [Riddhi9570/HackerrankPracticeProblems#195]
### Hackerrank problem link

Provide your hackerrank problem link here.

### Issue Checklist

* [ ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [ ] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by HarshitaSadadekar** [comment]
please assign me this issue

**Comment by Riddhi9570** [comment]
Please provide the hakerrank problem link you want to contribute. @HarshitaSadadekar

**Comment by HarshitaSadadekar** [comment]
https://www.hackerrank.com/challenges/c-tutorial-for-loop/problem

**Comment by Riddhi9570** [comment]
@RishitaGangwal And @HarshitaSadadekar These problem solutions are already present in the repo, you may please raise a new issue for another problem. Thanks!
