### ISSUE TITLE
The Power Sum

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#196]
Write your solution to this problem of hackerrank :-
Problem : [The Power Sum](https://www.hackerrank.com/challenges/the-power-sum/problem?isFullScreen=true)
Folder : Problem Solving/Algorithms/Recursion/The Power Sum
Language : C++/Java/Python
Difficulty : Medium

**Comment by achiverram28** [comment]
I will do this . Please assign

**Comment by RishitaGangwal** [comment]
Hey @Riddhi9570 Please assign me with this issue.

Thanks!

**Comment by achiverram28** [comment]
I have finished , please check it
