### ISSUE TITLE
Crossword Puzzle

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#197]
Write your solution to this problem of hackerrank :-
Problem : [Crossword Puzzle](https://www.hackerrank.com/challenges/crossword-puzzle/problem?isFullScreen=true)
Folder : Problem Solving/Algorithms/Recursion/Crossword Puzzle
Language : C++/Java/Python
Difficulty : Medium

**Comment by Samiatrix** [comment]
@Riddhi9570 Can I contribute in this issue?

**Comment by RishitaGangwal** [comment]
Hey @Riddhi9570 Would love to contribute. Please assign me with this issue.

Thanks!

**Comment by Riddhi9570** [comment]
@Samiatrix And @RishitaGangwal Which Programming language do you want to use with this problem?

**Comment by RishitaGangwal** [comment]
Hey @Riddhi9570 I would like to use Java Programming Language.

**Comment by RishitaGangwal** [comment]
Hey @Riddhi9570 I have submitted the code. Please check it once.

**Comment by Riddhi9570** [comment]
Hey, @RishitaGangwal , Nice to know that you are eager for the contribution😃!
Please note that it is considered a good practice to first wait till the issue is assigned to you, before working on it.

**Comment by RishitaGangwal** [comment]
Sorry for this mistake, it will not be happen again!

**Comment by Riddhi9570** [comment]
@RishitaGangwal Please create a PR for your changes and mention the issue for review. Thanks!

**Comment by Riddhi9570** [comment]
@Samiatrix You may give your solution in another language for this problem and add it in the same folder. 
Are you comfortable with C++ or Python?

**Comment by RishitaGangwal** [comment]
@Riddhi9570 Can you please share the github repo link so that I can open a pull request?

**Comment by RishitaGangwal** [comment]
Hey @Riddhi9570 Please mark this issue under hacktoberfest.

**Comment by Riddhi9570** [comment]
@RishitaGangwal 
- I'm sorry to inform you that unfortunately, further contributions to this repo won't be considered for hacktoberfest 2022.
- You may still contribute to this repository as open source and provide hackerrank problem solutions. Your contributions are always welcome!
- Also, if you are  new to github and looking to contribute to this repository as first time contributor before contributing to big projects, you are welcome!
- For Hacktoberfest 2022, you may look into some other projects.
- Thanks, happy Coding😃!
