### ISSUE TITLE
Recursive Digit Sum

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#198]
Write your solution to this problem of hackerrank :-
Problem : [Recursive Digit Sum](https://www.hackerrank.com/challenges/recursive-digit-sum/problem?isFullScreen=true)
Folder : Problem Solving/Algorithms/Recursion/The Power Sum
Language : C++/Java/Python
Difficulty : Medium

**Comment by abhi887449** [comment]
Hey @Riddhi9570 , assign this task to me

**Comment by abhi887449** [comment]
> Write your solution to this problem of hackerrank :- Problem : [Recursive Digit Sum](https://www.hackerrank.com/challenges/recursive-digit-sum/problem?isFullScreen=true) Folder : Problem Solving/Algorithms/Recursion/The Power Sum Language : C++/Java/Python Difficulty : Medium

Is i have to write code in 3 different files for c++, java and python or 1 file of any one language

**Comment by Riddhi9570** [comment]
One file of any language is required. But it would be appreciated if you could add all the three files.

**Comment by RishitaGangwal** [comment]
Hey, @Riddhi9570 I would love to contribute. Please assign this issue to me.

Thanks!

**Comment by abhi887449** [comment]
> One file of any language is required. But it would be appreciated if you could add all the three files.

Ok @Riddhi9570 , I would like to contribute in all three languages. Please assign this to me

**Comment by Riddhi9570** [comment]
Hey, @RishitaGangwal ,the issues are assigned on first-cum first-serve basis,  thanks.
