### ISSUE TITLE
JAVA : Java Stdin and Stdout I

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#20]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java Stdin and Stdout I](https://www.hackerrank.com/challenges/java-stdin-and-stdout-1/problem?isFullScreen=true)

**Comment by AmanGit010** [comment]
@Riddhi9570 Please assign this issue to me for Hacktoberfest 2022

**Comment by Rittika1234** [comment]
I am willing to contribute to this solution. As a part of hacktober-fest.
