### ISSUE TITLE
Maps-STL | c++

### ISSUE THREAD

**Issue by Akshun-01** [Riddhi9570/HackerrankPracticeProblems#202]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/cpp-maps/problem?isFullScreen=true
(first time contributor to this repo)

### Issue Checklist

* [ ] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [x] Your forked repo is up-to-date with the the origin remote.
* [x] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [x] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [x] Are you a Hacktoberfest Contributor?

**Comment by Riddhi9570** [comment]
@Akshun-01 This hackerrank problem is already present in the repo. You may please raise another issue with new hackerrank problem. Thanks!
