### ISSUE TITLE
This repo is now EXCLUDED from Hacktoberfest

### ISSUE THREAD

**Issue by AmanGit010** [Riddhi9570/HackerrankPracticeProblems#206]
@Riddhi9570 my 2 PRs are not accepted, they were in review period and got excluded now, we can stop people from contributing to this repo. :(

![image](https://user-images.githubusercontent.com/102356628/193546847-fb11ae0d-4e9b-4906-9ee6-78b037920a5d.png)

**Comment by sasidharswarangi** [comment]
same problem 😢
