### ISSUE TITLE
Maximizing XOR(Bit Manipulation) 

### ISSUE THREAD

**Issue by deepanshu-rawat6** [Riddhi9570/HackerrankPracticeProblems#209]
### Hackerrank problem link

Provide your hackerrank problem link here.
https://www.hackerrank.com/challenges/maximizing-xor/problem

### Issue Checklist

* [X] If you have previously contributed to this repo, you declare that you have not made a pull request for more than one issue in this repo till now.
* [X] Your forked repo is up-to-date with the the origin remote.
* [X] Have you checked that the hackerrank problem you are raising is not already present in the repo?
* [X] Have you checked that the hackerrank problem you are raising is not raised by or assigned to another contributor?

### Hacktoberfest Contributor

* [X] Are you a Hacktoberfest Contributor?

### Any other Changes?

If you are raising an issue with some more changes, please provide the details here.

**Comment by Riddhi9570** [comment]
Hey, thanks for raising an issue.
I'am regretting to inform you that this repository has now been excluded from hacktoberfest 2022.
You may take this issue as open source contribution. Thanks!

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.
