### ISSUE TITLE
JAVA : Java If-Else

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#21]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java If-Else](https://www.hackerrank.com/challenges/java-if-else/problem?isFullScreen=true)

**Comment by adityjoshi** [comment]
can I contribute to this issue

**Comment by Riddhi9570** [comment]
@adityjoshi Are you a hacktoberfest contributor?

**Comment by Rittika1234** [comment]
I am willing to contribute to this solution. As a part of hacktober-fest.

**Comment by Riddhi9570** [comment]
@Rittika1234 This issue has already been assigned to @adityjoshi . Yo may claim any other open and unassigned issue or create a new issue for different problem. All the best!

**Comment by adityjoshi** [comment]
@Riddhi9570 yes I am a Hacktoberfest contributor

**Comment by Riddhi9570** [comment]
@adityjoshi Please update your forked repo with the original repo and go ahead with the issue.

**Comment by adityjoshi** [comment]
hey @Riddhi9570 please review the code

**Comment by minhaj-313** [comment]
Hi, I  want to contribute in your Project, Can you please assign me for Hacktoberfest PR

**Comment by Riddhi9570** [comment]
Hey @minhaj-313 this issue is assigned to @adityjoshi . You can raise or claim another issue. Thanks!

**Comment by adityjoshi** [comment]
hey @Riddhi9570 made the changes please check

**Comment by adityjoshi** [comment]
Hey @Riddhi9570 have you added this to the main branch unable to see it on java folder

**Comment by Riddhi9570** [comment]
Hey @adityjoshi , thanks for asking. It is availaible [here](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/Java/01.%20Introduction/Java%20If-Else.java)
