### ISSUE TITLE
JAVA : Java Stdin and Stdout II

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#22]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java Stdin and Stdout II](https://www.hackerrank.com/challenges/java-stdin-stdout/problem?isFullScreen=true)

**Comment by dhruvbhatia1** [comment]
Can this issue be assigned to me?

**Comment by Rittika1234** [comment]
I am willing to contribute to this solution. As a part of hacktober-fest.

**Comment by dhruvbhatia1** [comment]
Yes I am a hacktoberfest contributor.

**Comment by Riddhi9570** [comment]
@Rittika1234 sorry, this issue was already assigned to @dhruvbhatia1. As per the norms, in any open source project, it is a good idea to start working on any issue only after it gets assigned to you.
