### ISSUE TITLE
JAVA : Java Loops II

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#25]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java Loops II](https://www.hackerrank.com/challenges/java-loops/problem?isFullScreen=true)

**Comment by kb-s** [comment]
@Riddhi9570 I want to contribute, it would be awesome if you please assign this to me 👍

**Comment by Riddhi9570** [comment]
@kb-s Are you a hacktoberfest contributor?

**Comment by kb-s** [comment]
@Riddhi9570 yes

**Comment by kb-s** [comment]
hey @Riddhi9570 1 file conflicted can you look into it, I guess README.md file

**Comment by kb-s** [comment]
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by kb-s** [comment]
hey @Riddhi9570 It's solved, it's my bad sorry

**Comment by SurbhiMotwani23** [comment]
I want to contribute,would be great if you could assign this to me

**Comment by kb-s** [comment]
@SurbhiMotwani23 I'm already working on it

**Comment by kb-s** [comment]
Hey @Riddhi9570, My pull request of this repo is excluded from HacktoberFest
