### ISSUE TITLE
JAVA : Java Datatypes

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#26]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java Datatypes](https://www.hackerrank.com/challenges/java-datatypes/problem?isFullScreen=true)

**Comment by Atharv-17** [comment]
kindly assign this to me under hacktoberfest '22

**Comment by RishitaGangwal** [comment]
Please assign this issue to me under hacktoberfest' 22

**Comment by Riddhi9570** [comment]
Hey @RishitaGangwal 
Nice to know that you are eager for the contribution😃!
But this issue is assigned to @Atharv-17 .
You may please raise or claim another issue. Thanks!

**Comment by RishitaGangwal** [comment]
Hey, please assign me another issue for hacktoberfest.
