### ISSUE TITLE
JAVA : Java Int to String

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#29]
Write your solution to this JAVA problem of hackerrank:-
Problem link : [Java Int to String](https://www.hackerrank.com/challenges/java-int-to-string/problem?isFullScreen=true)

**Comment by YashGupta018** [comment]
Please assign me, I'll work on this issue

**Comment by kb-s** [comment]
@Riddhi9570 I want to be assigned

**Comment by Rittika1234** [comment]
I am willing to contribute to this solution. As a part of hacktober-fest contributor

**Comment by saikishore222** [comment]
I am willing to contribute to the solution
