### ISSUE TITLE
SQL : 15 Days of Learning SQL

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#34]
Write your MySQL solution to this problem of hackerrank :-
Problem link : [15 Days of Learning SQL](https://www.hackerrank.com/challenges/15-days-of-learning-sql/problem?isFullScreen=true)

**Comment by 201B153** [comment]
assign it to me!!

**Comment by megha-vishwakarma** [comment]
Hello @Riddhi9570 could you Please assign this task to me. And please add Hacktoberfest tag. Thank you !
