### ISSUE TITLE
Python : Python If-Else

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#36]
Write your solution to this Python problem of hackerrank:-
Problem link : [Python If-Else](https://www.hackerrank.com/challenges/py-if-else/problem?isFullScreen=true)

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Can you please assign this issue to me with the hacktoberfest tag, as I have already completed this problem and have my solution ready?

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Can I please work on this now, as I have completed my previous issue
