### ISSUE TITLE
Python : Python: Division

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#38]
Write your solution to this Python problem of hackerrank:-
Problem link : [Python: Division](https://www.hackerrank.com/challenges/python-division/problem?isFullScreen=true)

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Could you please assign this issue to me as part of Hacktoberfest 2022

**Comment by Exoutia** [comment]
Can I take this issue

**Comment by Exoutia** [comment]
> Since I can assign only one issue to a contributor at a time, and have assigned another issue to @Prahmodh-R , I'm assigning this issue to @Exoutia . @Exoutia are you a hacktoberfest contributor?

Yes I am hacktoberfest contributor 😁😁 this is my first hacktoberfest

**Comment by Riddhi9570** [comment]
@Exoutia Nice to know! All the best with your journey!
