### ISSUE TITLE
Python : Loops

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#39]
Write your solution to this Python problem of hackerrank:-
Problem link : [Loops](https://www.hackerrank.com/challenges/python-loops/problem?isFullScreen=true)

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Could you please assign me this issue as part of Hacktoberfest 2022

**Comment by akshatjain1004** [comment]
Hey can I contribute to this issue as part of Hacktober fest 2022?

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Can you please assign this issue to me with the hacktoberfest tag, as I have already completed this problem and have my solution ready

**Comment by AyushJain001** [comment]
Hey, could you please assign this problem to me with hacktoberfest 2022 tag.

**Comment by SurbhiMotwani23** [comment]
please assign this problem to me

**Comment by Riddhi9570** [comment]
Since you all have been assigned another issue currently, and I cannot assign multiple issues to the same contributor at the same time, you may please continue working on the issue assigned to you. All the best!

**Comment by akshatjain1004** [comment]
@Riddhi9570 I'm not working on any issue right now, can I take this up?

**Comment by Riddhi9570** [comment]
Hey @akshatjain1004 since you have completed your previous issue, you can claim this issue now. Thanks!
