### ISSUE TITLE
Python : Write a function

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#41]
Write your solution to this Python problem of hackerrank :-
Problem link : [Write a function](https://www.hackerrank.com/challenges/write-a-function/problem?isFullScreen=true)

**Comment by raghav-rama** [comment]
How to go about this? Lyk the PR part. Not the solution part.

**Comment by Riddhi9570** [comment]
@raghav-rama You can follow [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md) and [pull_request_template.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/.github/pull_request_template.md).

You need to add your hackerrank solution to this repository and mention your hackerrank submitted solution link to verify your solution.

**Comment by raghav-rama** [comment]
Could you assign this to me under Hacktoberfest '22?
I want to work on this.

**Comment by Sowham-3098** [comment]
Please assign this task to me. And please add Hacktoberfest tag.

**Comment by P-Dhruva-Teja** [comment]
I have pulled a request for this problem.
