### ISSUE TITLE
small error in README.md

### ISSUE THREAD

**Issue by ayu8** [Riddhi9570/HackerrankPracticeProblems#45]
Hey @Riddhi9570 , there's a small error in the README.md of your file. 
Please assign this issue to me, I'll fix it

**Comment by Riddhi9570** [comment]
@ayu8 , what error do you see in README.md?

**Comment by Riddhi9570** [comment]
@ayu8 Thanks for pointing it out. But I cannot assign you this issue. You can claim any other open issue or create one new issue for a hackerrank practice problem solution for hacktoberfest. Happy coding!
