### ISSUE TITLE
Python: Finding The Percentage

### ISSUE THREAD

**Issue by akrishna5** [Riddhi9570/HackerrankPracticeProblems#47]
### Issue Number:

This submission will close the issue #47

### Submissions Checklist:

* [YES] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [YES] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [YES] Have you successfully submitted your code in hackerrank?
* [YES] Have you updated [README.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/README.md)?

### Hacktoberfest Contributor:

* [YES] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/finding-the-percentage/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/finding-the-percentage/submissions/code/293496203

### Any other changes you made or something you would like to mention?

NA

**Comment by mohantyrohan3** [comment]
Hey @akrishna5 Can you please assign the issue . I can work on it . And Please add the hacktoberfest label on the issue
