### ISSUE TITLE
Python : List Comprehensions

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#48]
Write your solution to this Python problem of hackerrank :-
Problem link : [List Comprehensions](https://www.hackerrank.com/challenges/list-comprehensions/problem?isFullScreen=true)

**Comment by Pargat-Dhanjal** [comment]
I would like to solve this. Can you assign me this?

**Comment by Riddhi9570** [comment]
@Pargat-Dhanjal are you a hacktoberfest contributor?

**Comment by Riddhi9570** [comment]
@Pargat-Dhanjal are you a hacktoberfest contributor?

**Comment by Pargat-Dhanjal** [comment]
@Riddhi9570 Yes
