### ISSUE TITLE
Python : Find the Runner-Up Score!

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#50]
Write your solution to this Python problem of hackerrank :-
Problem link : [Find the Runner-Up Score!](https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem?isFullScreen=true)

**Comment by aatharvauti** [comment]
Hello, can you please assign me this for the hacktoberfest?

**Comment by roshan71** [comment]
I want to contribute to this project.
Assign this project to me!!

**Comment by aatharvauti** [comment]
Hello @Riddhi9570, it seems that you didn't assign me for the issue

**Comment by SurbhiMotwani23** [comment]
please assign this to me

**Comment by ritikakr** [comment]
Please assign me this issue for hacktoberfest2022

**Comment by Arunjay126** [comment]
please assign this to me

**Comment by Dhruv-Mahajan1** [comment]
Hey @Riddhi9570 since this issue hasn't been allotted to anyone, can I work on it?
