### ISSUE TITLE
Java : Java Date and Time

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#51]
Write your solution to this Java problem of hackerrank :-
Problem link : [Java Date and Time](https://www.hackerrank.com/challenges/java-date-and-time/problem?isFullScreen=true)

**Comment by Pargat-Dhanjal** [comment]
@Riddhi9570 I am willing to contribute to this solution. As a part of hacktober-fest.

**Comment by Rittika1234** [comment]
I am willing to contribute to this solution

**Comment by AyushJain001** [comment]
Hey , I want to contribute . Could you please assign me with hacktoberfest tag
