### ISSUE TITLE
Python:Words Score

### ISSUE THREAD

**Issue by AyushJain001** [Riddhi9570/HackerrankPracticeProblems#57]
I am willing to contribute my code for the problem mentioned . Please assign this issue under hacktoberfest 2022 tag.
problem statement- https://www.hackerrank.com/challenges/words-score

**Comment by roshan71** [comment]
I am writing to contribute to this project.
Assign this project to me!!!

**Comment by Riddhi9570** [comment]
@AyushJain001 Sorry, I cannot assign multiple issues to the same contributor at a time. Once you complete that issue, you can claim this issue if it no one is assigned for this problem.

**Comment by Riddhi9570** [comment]
@roshan71 Sorry, this issue was raised by someone else. As per the norms, you can raise your own issue or claim an issue raised by the owner of the project. You may work on this issue if @AyushJain001 don't have any problem.

**Comment by AyushJain001** [comment]
Since I have completed my first issue #58 . I request to assign this to me under hacktoberfest 2022 tag
