### ISSUE TITLE
Java : Java Substring #64

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#64]
write your solution to this java problem of hackerrank :-
Problem link: https://www.hackerrank.com/challenges/java-substring/problem

**Comment by Rittika1234** [comment]
Please assign me this issue.

**Comment by Riddhi9570** [comment]
@Rittika1234 Have you checked this problem is not related to any other issue? If yes, then you may start working to this issue.

**Comment by dhirajmishra98** [comment]
I have done a lot of program in java. I want to contribute

**Comment by Riddhi9570** [comment]
@dhirajmishra98 You may raise an issue for a hackerrank problem of java, mentioning the problem link and please ensure that problem is not already raised in any issue or added to the repo. Thanks!
