### ISSUE TITLE
Java Inheritance I 

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#67]
write your solution to this java problem of hackerrank:-
Problem link: https://www.hackerrank.com/challenges/java-inheritance-1/problem

**Comment by Rittika1234** [comment]
can you please assign me this issue for hacktoberfest?

**Comment by sahilsarawagi** [comment]
please assign this to me for hacktoberfest.

**Comment by Riddhi9570** [comment]
@sahilsarawagi 
Hey, Thanks for raising an issue!
Nice to know that you are eager for the contribution😃!
Please note that it is considered a good practice to first wait till the issue is assigned to you, before working on it.
