### ISSUE TITLE
Java: Java Inheritance II #67

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#69]
I want to contribute my code for the problem mentioned . Please assign this under hacktoberfest 2022 tag.
Problem statement- https://www.hackerrank.com/challenges/java-inheritance-2/problem

**Comment by sahilsarawagi** [comment]
assign this to me.

**Comment by Riddhi9570** [comment]
@sahilsarawagi 
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
