### ISSUE TITLE
Java: Java 1D Array

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#70]
I want to contribute my code for the problem mentioned . Please assign this under hacktoberfest 2022 tag.
Problem statement- https://www.hackerrank.com/challenges/java-1d-array-introduction/problem

**Comment by AditUB** [comment]
Hey can I contribute to this?

**Comment by Riddhi9570** [comment]
@AditUB Go ahead!👍
