### ISSUE TITLE
Java: Java Abstract Class

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#71]
I want to contribute my code for the problem mentioned . Please assign this under hacktoberfest 2022 tag.
Problem statement- https://www.hackerrank.com/challenges/java-abstract-class/problem

**Comment by Riddhi9570** [comment]
Hey @sahilsarawagi 
I've assigned you the issue and you may please go ahead!
Happy Coding😃!
