### ISSUE TITLE
Java: Java Interface

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#72]
I want to contribute my code for the problem mentioned . Please assign this under hacktoberfest 2022 tag.
Problem statement- https://www.hackerrank.com/challenges/java-interface/problem

**Comment by adityjoshi** [comment]
hey @Riddhi9570 can I contribute to this issue

**Comment by Riddhi9570** [comment]
Hey, @adityjoshi I've assigned you the issue and you may please go ahead!
Happy Coding😃!

**Comment by RishitaGangwal** [comment]
Hey, I would like to contribute to this issue.

**Comment by Riddhi9570** [comment]
Hey, @RishitaGangwal, this issue is assigned to @adityjoshi . You can raise a new issue for another problem. Thanks!
