### ISSUE TITLE
Java: Java Method Overriding

### ISSUE THREAD

**Issue by Rittika1234** [Riddhi9570/HackerrankPracticeProblems#74]
I want to contribute my code for the problem mentioned . Please assign this under hacktoberfest 2022 tag.
Problem statement- https://www.hackerrank.com/challenges/java-method-overriding

**Comment by Riddhi9570** [comment]
@sahilsarawagi Hey, Thanks for taking the issue😃!
Please note that it is considered a good practice to first wait till the issue is assigned to you, before working on it.
