### ISSUE TITLE
C++ : Pointer

### ISSUE THREAD

**Issue by PurviSaini** [Riddhi9570/HackerrankPracticeProblems#76]
I would like to contribute the solution for the problem: https://www.hackerrank.com/challenges/c-tutorial-pointer/problem?isFullScreen=true 
Kindly tag it under hacktoberfest.

**Comment by Riddhi9570** [comment]
Hey, @PurviSaini Thanks for raising an issue. But this issue is already raised in #14 . You may please comment there and claim the issue.
