### ISSUE TITLE
C++ : Say "Hello, World!" With C++

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#8]
Write your solution to this C++ problem of hackerrank:-
Problem link : [Say "Hello, World!" With C++](https://www.hackerrank.com/challenges/cpp-hello-world/problem?isFullScreen=true)

**Comment by kataranandini** [comment]
please assign also to me under hacktober tag

**Comment by Riddhi9570** [comment]
@kataranandini This issue has already been assigned to someone else. You may claim any other open issue or create your own issue.
