### ISSUE TITLE
Rectangle Area

### ISSUE THREAD

**Issue by Dhruv-Mahajan1** [Riddhi9570/HackerrankPracticeProblems#82]
Write a solution to this Hackerrank problem : [Link](https://www.hackerrank.com/challenges/rectangle-area/problem)
@Riddhi9570 can I work on this issue

**Comment by Riddhi9570** [comment]
@Dhruv-Mahajan1 Hey, Thanks for raising an issue. You may complete your previous issue before claiming this issue. Happy Coding!

**Comment by Dhruv-Mahajan1** [comment]
@Riddhi9570  I am done with my previously assigned issue can I start working on the above-mentioned issue?
Thanks!

**Comment by Riddhi9570** [comment]
@Dhruv-Mahajan1 Go ahead!
