### ISSUE TITLE
Java Question

### ISSUE THREAD

**Issue by panditsamik** [Riddhi9570/HackerrankPracticeProblems#86]
I want to contribute a program in JAVA on Pascal's Triangle.

**Comment by Riddhi9570** [comment]
@panditsamik Thanks for raising an issue! Please mention the link of the problem you would like to work on and please ensure that it is not already present in the repo and it is not raised in an issue by someone else.

**Comment by panditsamik** [comment]
@Riddhi9570  I want to work on Java Stack
Link - https://www.hackerrank.com/challenges/java-stack/problem?isFullScreen=true

**Comment by Riddhi9570** [comment]
@panditsamik Go ahead!
