### ISSUE TITLE
C++ : Input and Output

### ISSUE THREAD

**Issue by Riddhi9570** [Riddhi9570/HackerrankPracticeProblems#9]
Write your solution to this C++ problem of hackerrank :-
Problem link : [Input and Output](https://www.hackerrank.com/challenges/cpp-input-and-output/problem?isFullScreen=true)

**Comment by abhi887449** [comment]
Please assign this to me

**Comment by Riddhi9570** [comment]
@abhi887449 Are you a hacktoberfest contributor?

**Comment by abhi887449** [comment]
> @abhi887449 Are you a hacktoberfest contributor?

yes

**Comment by Riddhi9570** [comment]
@abhi887449 Alright, go ahead!
