### ISSUE TITLE
check if the given string is palindrome or not .

### ISSUE THREAD

**Issue by dhirajmishra98** [Riddhi9570/HackerrankPracticeProblems#94]

**Comment by dhirajmishra98** [comment]
Check if the give string is palindrome or not in java.
Problem link : https://www.hackerrank.com/challenges/java-string-reverse/problem

**Comment by AmanGit010** [comment]
@dhirajmishra98 please assign this issue to me for Hacktoberfest 2022.

**Comment by dhirajmishra98** [comment]
please do

**Comment by Riddhi9570** [comment]
Sorry, this hackerrank problem has already been raised in the issue #44.
